## numpy 

In [ ]:
1.) Numerical python
2.) Written in c
3.) fast
4.) python package used for com[putation and processing of single/multidimensional array
4.)provide  efficient way to handle large amount of data. 

In [4]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.8 MB 6.7 MB/s eta 0:00:02
   ------ --------------------------------- 2.1/12.8 MB 5.3 MB/s eta 0:00:02
   --------- ------------------------------ 2.9/12.8 MB 4.8 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.8 MB 4.5 MB/s eta 0:00:03
   -------------- ------------------------- 4.7/12.8 MB 4.5 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.8 MB 4.4 MB/s eta 0:00:02
   ------------------ --------------------- 6.0/12.8 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.8 MB 4.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.8 MB 4.3 MB/s eta 0:00:02
   --------------------------- ------------ 8.9/12.8 MB 4.4 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.8 MB 4.4 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.8 MB 4.4 MB/s eta 0:00:01
   -


[notice] A new release of pip is available: 24.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
#list/tuple
import numpy as np
a = [1,2,3,4,5]
data = np.array(a)
print(data , type(data))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:

a = 1,2,3,4,5
data = np.array(a)
print(data , type(data))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [10]:
a = [[1,2],[3,4],[5,6]]
data = np.array(a)
print(data , type(data))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


In [12]:
# attribute 
# size - count of elements
print(data.size)

6


In [13]:
# shape - it tells the shape of an array - always in tuple
print(data.shape)

(3, 2)


In [14]:
# ndim - it tells the dimension of an array
print(data.ndim)

2


In [16]:
#2. arange function
np.arange(0,10,3)    # data will be in form of array

array([0, 3, 6, 9])

In [19]:
import numpy as np
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
import numpy as np
np.random.random_integers(10,20,(5,10))

C:\Users\PTC-SW\AppData\Local\Temp\ipykernel_23880\1364754915.py:2: DeprecationWarning: This function is deprecated. Please call randint(10, 20 + 1) instead
  np.random.random_integers(10,20,(5,10))


array([[17, 14, 11, 20, 18, 14, 11, 11, 13, 13],
       [11, 19, 15, 16, 10, 13, 20, 11, 16, 18],
       [13, 14, 13, 17, 17, 14, 17, 10, 10, 15],
       [10, 14, 14, 16, 16, 13, 15, 19, 17, 16],
       [18, 14, 17, 20, 11, 14, 12, 15, 13, 15]], dtype=int32)

In [8]:
np.random.random((2,3))

array([[0.18464949, 0.45364386, 0.03196285],
       [0.00121762, 0.58333116, 0.89602295]])

In [ ]:
# changing the dimension and shape of an array
Reshape
1D - 2D
dimension = no.of elements

In [14]:
import numpy as np
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [17]:
a.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
a.reshape(1,10,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [19]:
a.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [20]:
# transpose
data = np.arange(0,20).reshape(5,4)
data, data.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 (5, 4))

In [21]:
data.T  # transpose function

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [22]:
# infer
data = np.arange(0,1000).reshape(2,5,50,2)
data , data.shape

(array([[[[  0,   1],
          [  2,   3],
          [  4,   5],
          [  6,   7],
          [  8,   9],
          [ 10,  11],
          [ 12,  13],
          [ 14,  15],
          [ 16,  17],
          [ 18,  19],
          [ 20,  21],
          [ 22,  23],
          [ 24,  25],
          [ 26,  27],
          [ 28,  29],
          [ 30,  31],
          [ 32,  33],
          [ 34,  35],
          [ 36,  37],
          [ 38,  39],
          [ 40,  41],
          [ 42,  43],
          [ 44,  45],
          [ 46,  47],
          [ 48,  49],
          [ 50,  51],
          [ 52,  53],
          [ 54,  55],
          [ 56,  57],
          [ 58,  59],
          [ 60,  61],
          [ 62,  63],
          [ 64,  65],
          [ 66,  67],
          [ 68,  69],
          [ 70,  71],
          [ 72,  73],
          [ 74,  75],
          [ 76,  77],
          [ 78,  79],
          [ 80,  81],
          [ 82,  83],
          [ 84,  85],
          [ 86,  87],
          [ 88,  89],
          

In [24]:
#conevrt it into 2 dimensiona such that no.of rows should be 50
data.reshape(50,-1)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,
         33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
        153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 1

In [25]:
data.reshape(-1,2)

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9],
       [ 10,  11],
       [ 12,  13],
       [ 14,  15],
       [ 16,  17],
       [ 18,  19],
       [ 20,  21],
       [ 22,  23],
       [ 24,  25],
       [ 26,  27],
       [ 28,  29],
       [ 30,  31],
       [ 32,  33],
       [ 34,  35],
       [ 36,  37],
       [ 38,  39],
       [ 40,  41],
       [ 42,  43],
       [ 44,  45],
       [ 46,  47],
       [ 48,  49],
       [ 50,  51],
       [ 52,  53],
       [ 54,  55],
       [ 56,  57],
       [ 58,  59],
       [ 60,  61],
       [ 62,  63],
       [ 64,  65],
       [ 66,  67],
       [ 68,  69],
       [ 70,  71],
       [ 72,  73],
       [ 74,  75],
       [ 76,  77],
       [ 78,  79],
       [ 80,  81],
       [ 82,  83],
       [ 84,  85],
       [ 86,  87],
       [ 88,  89],
       [ 90,  91],
       [ 92,  93],
       [ 94,  95],
       [ 96,  97],
       [ 98,  99],
       [100, 101],
       [102, 103],
       [104,

In [26]:
data.reshape(2,5,-1)

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,
          12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,
          24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
          36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
          48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
          60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,
          72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
          96,  97,  98,  99],
        [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123,
         124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135,
         136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
         148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159,
         160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
    

In [ ]:
#Flattened/ravel

In [27]:
#convert higher dimension matrix into 1 dimension matrix.
data = np.arange(0,20).reshape(5,4)
data, data.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 (5, 4))

In [28]:
data.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
data.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
# basic operations with array.
a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])

In [31]:
a+b

array([11, 22, 33, 44, 55])

In [32]:
a-b

array([ 9, 18, 27, 36, 45])

In [33]:
a*b

array([ 10,  40,  90, 160, 250])

In [34]:
a/b

array([10., 10., 10., 10., 10.])

In [35]:
a%2

array([0, 0, 0, 0, 0])

In [36]:
a>15

array([False,  True,  True,  True,  True])

In [37]:
a**2

array([ 100,  400,  900, 1600, 2500])

In [ ]:
#while - doing any operation with a matrix make sure that both the matrix has the same shape

In [38]:
#matrix multiplication /dot product
array_1 = np.array([[1,2,3],[4,5,6]])

In [39]:
array_1

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
array_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [41]:
array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
array_1.shape

(2, 3)

In [44]:
array_2.shape

(3, 3)

In [45]:
array_1.dot(array_2)

array([[30, 36, 42],
       [66, 81, 96]])

In [48]:
#Unary operation
array = np.array([4,5,6,7,3,4,5])

In [54]:
# sum of all the elements
print(array.sum())

34


In [55]:
print(array.min())

3


In [56]:
print(array.max())

7


In [57]:
print(array.mean())

4.857142857142857


In [59]:
array = np.array([4,3,2,5,6,7,8,3,1,2]).reshape(5,2)

In [60]:
array

array([[4, 3],
       [2, 5],
       [6, 7],
       [8, 3],
       [1, 2]])

In [61]:
array.sum(axis = 1)

array([ 7,  7, 13, 11,  3])

In [62]:
array.sum(axis = 0)

array([21, 20])

In [ ]:
# indexing and slicing in array

In [ ]:
# indexing with 1 dim

In [64]:
a = np.arange(3,10)

In [65]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [70]:
array = np.array([4,3,2,5,6,7]).reshape(3,2)

In [71]:
array

array([[4, 3],
       [2, 5],
       [6, 7]])

In [74]:
array[1,1]

np.int64(5)

In [80]:
array[-6:-3:-1]

array([], shape=(0, 2), dtype=int64)

In [81]:
a[0:6]

array([3, 4, 5, 6, 7, 8])

In [82]:
a[0:6:2]

array([3, 5, 7])

In [86]:
array = np.array([4,3,2,5,6,7,10,11,12,13,14,15]).reshape(4,3)

In [87]:
array

array([[ 4,  3,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [13, 14, 15]])

In [89]:
array[1:3,1:]

array([[ 6,  7],
       [11, 12]])

In [3]:
import numpy as np
a = np.arange(0,25)*23
a.reshape(5,5)

array([[  0,  23,  46,  69,  92],
       [115, 138, 161, 184, 207],
       [230, 253, 276, 299, 322],
       [345, 368, 391, 414, 437],
       [460, 483, 506, 529, 552]])

In [4]:
a

array([  0,  23,  46,  69,  92, 115, 138, 161, 184, 207, 230, 253, 276,
       299, 322, 345, 368, 391, 414, 437, 460, 483, 506, 529, 552])

In [5]:
a.shape

(25,)

In [6]:
a

array([  0,  23,  46,  69,  92, 115, 138, 161, 184, 207, 230, 253, 276,
       299, 322, 345, 368, 391, 414, 437, 460, 483, 506, 529, 552])

In [7]:
a.reshape(5,5)

array([[  0,  23,  46,  69,  92],
       [115, 138, 161, 184, 207],
       [230, 253, 276, 299, 322],
       [345, 368, 391, 414, 437],
       [460, 483, 506, 529, 552]])

In [8]:
array = a.reshape(5,5)

In [9]:
array[2:4,1:4]

array([[253, 276, 299],
       [368, 391, 414]])

In [11]:
array[1:4:2,1:4:2]

array([[138, 184],
       [368, 414]])

In [12]:
# extraxt 161,184,276,299
array[1:3,2:4]

array([[161, 184],
       [276, 299]])